apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-news.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-news.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  API_PORT: {{ .Values.env.apiPort | quote }}
  WEB_PORT: {{ .Values.env.webPort | quote }}
  CORS_ORIGIN: {{ .Values.env.corsOrigin | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.env.nextPublicApiUrl | quote }}
