{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  # This name MUST match the kube-news.dbHost helper output
  name: {{ include "kube-news.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 5432
      targetPort: 5432
  # ClusterIP — database is never exposed outside the cluster
  type: ClusterIP
{{- end }}
