apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-news.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-news.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  DATABASE_URL: {{ include "kube-news.databaseUrl" . | quote }}
