apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-news.webFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      {{- if eq .Values.web.service.type "NodePort" }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  type: {{ .Values.web.service.type }}
