apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kube-news
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  # ClusterIP — Postgres is internal only, never exposed outside the cluster
  type: ClusterIP
