apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news-web
  namespace: kube-news
  labels:
    app: kube-news-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-news-web
  template:
    metadata:
      labels:
        app: kube-news-web
    spec:
      containers:
        - name: kube-news-web
          image: goldenglowitsolutions/kube-news-web:2.0.0
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: kube-news-config
                  key: WEB_PORT
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kube-news-config
                  key: NEXT_PUBLIC_API_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
